server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:

      # CONFIGURACION DE CORS GLOBAL
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowerdHeaders: "*"

      routes:
        # Ruta para reservas
        - id: service-reservas
          uri: http://localhost:8084
          predicates:
          - Path=/api/v3/reservas/**

        # Ruta para documentación reservas
        - id: reservas-docs
          uri: http://localhost:8084
          predicates:
          - Path=/api/v3/reservas/v3/api-docs

        # Ruta para logistica
        - id: service-logistica
          uri: http://localhost:8085
          predicates:
          - Path=/api/v4/logistica/**

        # Ruta para documentación logistica
        - id: logistica-docs
          uri: http://localhost:8085
          predicates:
          - Path=/api/v4/logistica/v3/api-docs

        # Ruta para comprobantes
        - id: service-comprobantes
          uri: http://localhost:8088
          predicates:
          - Path=/api/v1/comprobantes, /api/v1/comprobantes/**

        # Ruta para documentación comprobantes
        - id: comprobantes-docs
          uri: http://localhost:8088
          predicates:
          - Path=/api/v1/comprobantes/v3/api-docs
        
        # Ruta para devoluciones
        - id: service-devoluciones
          uri: http://localhost:8090
          predicates:
          - Path=/api/v1/devoluciones, /api/v1/devoluciones/**

        # Ruta para documentación devoluciones
        - id: devoluciones-docs
          uri: http://localhost:8090
          predicates:
          - Path=/api/v1/devoluciones/v3/api-docs

        # ------------------- NUEVOS MICROSERVICIOS -------------------

        # Ruta para catalogo (Productos)
        - id: service-catalogo
          uri: http://localhost:8081
          predicates:
          - Path=/api/v1/productos, /api/v1/productos/**

        - id: catalogo-docs
          uri: http://localhost:8081
          predicates:
          - Path=/api/v1/productos/v3/api-docs

        # Ruta para carrito
        - id: service-carrito
          uri: http://localhost:8083
          predicates:
          - Path=/api/v1/carritos, /api/v1/carritos/**

        - id: carrito-docs
          uri: http://localhost:8083
          predicates:
          - Path=/api/v1/carritos/v3/api-docs

        # Ruta para inventario
        - id: service-inventario
          uri: http://localhost:8082
          predicates:
          - Path=/api/v1/inventario, /api/v1/inventario/**

        - id: inventario-docs
          uri: http://localhost:8082
          predicates:
          - Path=/api/v1/inventario/v3/api-docs

        # Ruta para promociones (Cupones)
        - id: service-promociones
          uri: http://localhost:8086
          predicates:
          - Path=/api/v1/cupones, /api/v1/cupones/**

        - id: promociones-docs
          uri: http://localhost:8086
          predicates:
          - Path=/api/v1/cupones/v3/api-docs

        # Ruta para reembolsos
        - id: service-reembolsos
          uri: http://localhost:8087
          predicates:
          - Path=/api/v1/reembolsos, /api/v1/reembolsos/**

        - id: reembolsos-docs
          uri: http://localhost:8087
          predicates:
          - Path=/api/v1/reembolsos/v3/api-docs

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    urls:
      - name: Servicio Reservas
        url: /api/v3/reservas/v3/api-docs
      - name: Servicio Logistica
        url: /api/v4/logistica/v3/api-docs
      - name: Servicio Comprobantes
        url: /api/v1/comprobantes/v3/api-docs
      - name: Servicio Devoluciones
        url: /api/v1/devoluciones/v3/api-docs
      - name: Servicio Catalogo
        url: /api/v1/productos/v3/api-docs
      - name: Servicio Carrito
        url: /api/v1/carritos/v3/api-docs
      - name: Servicio Inventario
        url: /api/v1/inventario/v3/api-docs
      - name: Servicio Promociones
        url: /api/v1/cupones/v3/api-docs
      - name: Servicio Reembolsos
        url: /api/v1/reembolsos/v3/api-docs