server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:

      # CONFIGURACION DE CORS GLOBAL
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowerdHeaders: "*"

      routes:
        # Ruta para reservas
        - id: service-reservas
          uri: http://localhost:8084
          predicates:
          - Path=/api/v3/reservas/**

        # Ruta para documentación reservas
        - id: reservas-docs
          uri: http://localhost:8084
          predicates:
          - Path=/api/v3/reservas/v3/api-docs



        # Ruta para logistica
        - id: service-logistica
          uri: http://localhost:8085
          predicates:
          - Path=/api/v4/logistica/**

        # Ruta para documentación logistica
        - id: logistica-docs
          uri: http://localhost:8085
          predicates:
          - Path=/api/v4/logistica/v3/api-docs



        # Ruta para comprobantes
        - id: service-comprobantes
          uri: http://localhost:8088
          predicates:
          - Path=/api/v1/comprobantes, /api/v1/comprobantes/**

        # Ruta para documentación comprobantes
        - id: comprobantes-docs
          uri: http://localhost:8088
          predicates:
          - Path=/api/v1/comprobantes/v3/api-docs
        


        # Ruta para devoluciones
        - id: service-devoluciones
          uri: http://localhost:8090
          predicates:
          - Path=/api/v1/devoluciones, /api/v1/devoluciones/**

        # Ruta para documentación devoluciones
        - id: devoluciones-docs
          uri: http://localhost:8090
          predicates:
          - Path=/api/v1/devoluciones/v3/api-docs

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    urls:
      - name: Servicio Reservas
        url: /api/v3/reservas/v3/api-docs
      - name: Servicio Logistica
        url: /api/v4/logistica/v3/api-docs
      - name: Servicio Comprobantes
        url: /api/v1/comprobantes/v3/api-docs
      - name: Servicio Devoluciones
        url: /api/v1/devoluciones/v3/api-docs